### ISSUE TITLE
Specifying year does not result in the expected behaviour

### ISSUE THREAD

**Issue by hgaronfolo** [zappingseb/analyze_last_fm#1]
Hi, I am confused about this behaviour, and I think there might be a bug?

![image](https://user-images.githubusercontent.com/10169439/52115279-80929b00-260e-11e9-9749-606777870568.png)

I would expect that the data from 2003 would be downloaded.. and not the 2019 scrobbles.

Thanks for sharing your work!

Best regards,
Herbert

**Comment by zappingseb** [comment]
Done by PR #2
