### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by mharrisonbaker** [zappingseb/analyze_last_fm#4]
fresh install of R and updated all packages...

using 
> devtools::install_github("zappingseb/analyze_last_fm")
 I get

Installing package into ‘C:/Users/Matt/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'analyzelastfm' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'jsonlite' was built under R version 3.5.3
ERROR: lazy loading failed for package 'analyzelastfm'
* removing 'C:/Users/Matt/Documents/R/win-library/3.5/analyzelastfm'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Matt/AppData/Local/Temp/RtmpmwnTMk/file430c46db7a6e/analyzelastfm_0.1.tar.gz’ had non-zero exit status

**Comment by zappingseb** [comment]
This is a pretty common issue in Windows + R

Please download the tar.gz of this package from here: https://github.com/zappingseb/analyze_last_fm/releases/download/v0.1/analyzelastfm_0.1.tar.gz

Install it via

```r
install.packages("analyzelastfm_0.1.tar.gz", repos = NULL)
```

This should work.

You can also update your R-Version to `3.5.3` and the issue will be gone
